development:
  twitterConsumerSecret: "Vpe30kLyYimojc9tkmn6dkWcOQH45HdmNg2RhMkuJ3ojvCgrRU"
  twitterConsumerKey: "QgFI3zykukaEb2TiHJ44OJt9C"
  fabricKey: "61fec037830f072a57601a3e9f538a4a0f0d1ac3"
staging:
  twitterConsumerSecret: "x"
  twitterConsumerKey: "x"
  fabricKey: "x"
production:
  twitterConsumerSecret: "x"
  twitterConsumerKey: "x"
  fabricKey: "x"
